project:
  type: website

website:
  title: "NESBp"
  navbar:
    left:
      - text: Explanation
        href: explanation.qmd
      - text: Policy Makers
        href: policy_makers.qmd
      - text: MSP Experts
        href: msp_experts.qmd
      - text: Sectorial Actors
        href: sectorial_actors.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



