project:
  type: website

website:
  title: "NESBp"
  navbar:
    left:
      - text: Explanation
        href: explanation.qmd
      - text: Policy Makers
        href: policy_makers.qmd
      - text: MSP Experts
        href: msp_experts.qmd
      - text: Sectorial Actors
        href: sectorial_actors.qmd

  sidebar:
    - title: "Policy Makers"
      style: "docked"
      background: light
      contents:
        - text: "Policy Makers"
          href: policy_makers.qmd
        - text: "Policy Makers 1"
          href: policy_makers_1.qmd
        - text: "Policy Makers 2"
          href: policy_makers_2.qmd
        - text: "Policy Makers 3"
          href: policy_makers_3.qmd
        - text: "Policy Makers 4"
          href: policy_makers_4.qmd

    - title: "MSP Experts"
      contents:
        - text: "MSP Experts"
          href: msp_experts.qmd
        - text: "MSP Experts 1"
          href: msp_experts_1.qmd
        - text: "MSP Experts 2"
          href: msp_experts_2.qmd
        - text: "MSP Experts 3"
          href: msp_experts_3.qmd

    - title: "Sectorial Actors"
      contents:
        - text: "Sectorial Actors"
          href: sectorial_actors.qmd
        - text: "Sectorial Actors 1"
          href: sectorial_actors_1.qmd
        - text: "Sectorial Actors 2"
          href: sectorial_actors_2.qmd




format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



