project:
  pre-render:
    - "python generate_quarto_nav.py nodes.csv --yml-out _quarto.yml --create-stubs --sidebar-style docked --sidebar-background light --sidebar-collapse-level 1 --logo assets/GNSBI_NESBp_combined.png"
  resources:
    - nodes.csv
    - page_content.csv
    - assets/GNSBI_NESBp_combined.png
  type: website

execute:
  freeze: auto

website:
  title: "NESBp MSP knowledge sharing platform"
  navbar:
    logo: assets/GNSBI_NESBp_combined.png
    left:
      - text: "Policy Makers"
        href: policy_makers.qmd
      - text: "MSP Experts"
        href: msp_experts.qmd

  sidebar:
    - title: "Policy Makers"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "Policy Makers"
          href: policy_makers.qmd
        - section: "Knowledge Base for Decisions"
          href: policy_makers_knowledge_base.qmd
          contents:
            - text: "Boundaries and Windfarms"
              href: boundaries-and-windfarms.qmd
            - text: "Nature Restoration and Conservation"
              href: policy_makers_nature.qmd
            - text: "Multi-use"
              href: policy_makers_multi_use.qmd
            - text: "Cumulative Impacts Assessment (CIA)"
              href: policy_makers_cia.qmd
            - text: "Long-term Perspective of Fisheries"
              href: policy_makers_fisheries.qmd
            - text: "Shipping"
              href: policy_makers_case_shipping.qmd
        - section: "MSP Administrative boundaries"
          href: msp-administrative-boundaries.qmd
          contents:
            - text: "Exclusive Economic Zones"
              href: exclusive-economic-zones.qmd
            - text: "OSPAR Regions"
              href: ospar-regions.qmd
            - text: "GNSBI Boundaries"
              href: gnsbi-boundaries.qmd
            - text: "NSEC Boundaries"
              href: nsec-boundaries.qmd
            - text: "Territorial Seas (12nm)"
              href: territorial-seas-12nm.qmd
        - section: "MSP Zoning"
          href: policy_makers_msp_zoning.qmd
          contents:
            - text: "Planned sea use data"
              href: policy_makers_planned_sea_use.qmd
        - section: "National MSP plan maps"
          href: national-msp-plan-maps.qmd
          contents:
            - text: "Netherlands"
              href: policy_makers_msp_zoning_NL.qmd
            - text: "Germany"
              href: policy_makers_msp_zoning_GE.qmd
            - text: "Belgium"
              href: policy_makers_msp_zoning_BE.qmd
            - text: "Denmark"
              href: policy_makers_msp_zoning_DK.qmd
            - text: "Norway"
              href: policy_makers_msp_zoning_NO.qmd
            - text: "England"
              href: policy_makers_msp_zoning_EN.qmd
            - text: "France"
              href: policy_makers_msp_zoning_FR.qmd
            - text: "Sweden"
              href: policy_makers_msp_zoning_SE.qmd
            - text: "Scotland"
              href: policy_makers_msp_zoning_SC.qmd
            - text: "Ireland"
              href: policy_makers_msp_zoning_IE.qmd

    - title: "MSP Experts"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "MSP Experts"
          href: msp_experts.qmd
        - section: "MSP Input Data"
          href: msp_experts_msp_input.qmd
          contents:
            - text: "MSP input Netherlands"
              href: msp_experts_msp_input_NL.qmd
            - text: "MSP input Germany"
              href: msp_experts_msp_input_GE.qmd
            - text: "MSP input Belgium"
              href: msp_experts_msp_input_BE.qmd
            - text: "MSP input Denmark"
              href: msp_experts_msp_input_DK.qmd
            - text: "MSP input Norway"
              href: msp_experts_msp_input_NO.qmd
            - text: "MSP input England"
              href: msp_experts_msp_input_EN.qmd
            - text: "MSP input France"
              href: msp_experts_msp_input_FR.qmd
            - text: "MSP input Sweden"
              href: msp_experts_msp_input_SE.qmd
            - text: "MSP input Scotland"
              href: msp_experts_msp_input_SC.qmd
            - text: "MSP input Ireland"
              href: msp_experts_msp_input_IE.qmd
        - text: "Knowledge Base for Decisions"
          href: msp_experts_knowledge_base.qmd
        - text: "MSP Zoning"
          href: msp_experts_msp_zoning.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
