project:
  type: website

website:
  title: "NESBp"
  navbar:
    left:
      - text: Input Data
        href: input_data.qmd
      - text: Knowledge Base
        href: knowledge_base.qmd
      - text: MSP Zoning
        href: msp_zoning.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



