---
title: "Untitled"
format: dashboard
---


# Input map layers

## Sidebar {.sidebar}

**Input Map Categories**

- Nature
  - MPA
  - Biodiversity
- Fisheries
  - Intensity
- Energy


# Input map layers

## Row

### column

```{=html}
<iframe style="border:none;" height="600" width="100%" src="https://viewer.openearth.nl/compendium-greater-north-sea/?folders=143750791,143750761&layers=143750774&layerNames=OSPAR%20MPA%202023%20%28OSPAR%29"></iframe>
```

### Column

```{=html}
<iframe style="border:none;" height="600" width="100%" src="https://testsysteemrapportage.nl/compendium-greater-north-sea/nature.html#marine-biodiversity-and-protected-areas"></iframe>
```


# Output map layers

## Sidebar {.sidebar}

**Output Map Categories**

- Land Use Summary
  - Table
  - ECharts Graph
- Data Visualizations
  - Penguin Example
- Reports
  - Downloadable Data

## Row

### column

```{=html}
<iframe style="border:none;" height="600" width="100%" src="https://viewer.openearth.nl/compendium-greater-north-sea/?folders=143750791,143750761&layers=143750774&layerNames=OSPAR%20MPA%202023%20%28OSPAR%29"></iframe>
```

### Column

| Country      | Shipping | Fishing | Energy | Nature Protection |
|--------------|----------|---------|--------|------------------|
| Netherlands  |   X      |   ✓     |   ✓    |        ✓         |
| Germany      |   ✓      |   ✓     |   ✓    |        X         |
| Denmark      |   ✓      |   ✓     |   ✓    |        ✓         |
| UK           |   X      |   ✓     |   ✓    |        ✓         |
| Belgium      |   ✓      |   X     |   ✓    |        ✓         |
| Norway       |   ✓      |   X     |   ✓    |        ✓         |

<small>Table: Example Marine Land Uses per country in the North Sea (✓ = present)</small>
<br>

<!-- ECharts library -->
<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js"></script>

<!-- ECharts container -->
<div id="marine-uses-chart" style="width: 600%; height: 400px;"></div>

<script>
  var chartDom = document.getElementById('marine-uses-chart');
  var myChart = echarts.init(chartDom);
  var option = {
    title: {
      text: 'Marine Land Uses per Country (Example)',
      left: 'center'
    },
    tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } },
    legend: { top: 30 },
    grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
    xAxis: {
      type: 'category',
      data: ['Netherlands', 'Germany', 'Denmark', 'UK', 'Belgium', 'Norway']
    },
    yAxis: { type: 'value', min: 0, max: 4, interval: 1, name: 'Number of Uses' },
    series: [
      {
        name: 'Shipping',
        type: 'bar',
        stack: 'uses',
        data: [0, 1, 1, 0, 1, 1],
        itemStyle: { color: '#5470C6' }
      },
      {
        name: 'Fishing',
        type: 'bar',
        stack: 'uses',
        data: [1, 1, 1, 1, 0, 0],
        itemStyle: { color: '#91CC75' }
      },
      {
        name: 'Energy',
        type: 'bar',
        stack: 'uses',
        data: [1, 1, 1, 1, 1, 1],
        itemStyle: { color: '#FAC858' }
      },
      {
        name: 'Nature Protection',
        type: 'bar',
        stack: 'uses',
        data: [1, 0, 1, 1, 1, 1],
        itemStyle: { color: '#EE6666' }
      }
    ]
  };
  myChart.setOption(option);
</script>